### ISSUE TITLE
Iron Router settings

### ISSUE THREAD

**Issue by imajus** [yogiben/meteor-notifications#3]
Thanks for a great package it works perfectly out of box. There's one small issue I'd like to address though. You have routes setup in your `lib/both/router.coffee` which may conflict with application's router settings. And it does in my case because I have a router called 'messages' already. 
I could rename my router but that's not right way to fix that. Instead, could you use prefix in your router names? For example, `@route 'yogiben.messages'` instead of `@route 'messages',` and the same for 'notifications' router.
Also I don't actually need these pages at all cause I'd like to use existing ones in my application. Will you add a package configuration which will disable these routes at all?

**Comment by etmarch** [comment]
I also agree with this, lets namespace the 'messages' route correctly, as 'messages' can be a somewhat common name.
